### ISSUE TITLE
Bug/feature report

### ISSUE THREAD

**Issue by jussmen** [jussmen/WebSocket_cURL#1]
Please give me your feedback here

**Comment by seremenko** [comment]
I just got this error:

Traceback (most recent call last):
  File "WebSocket_cURL.py", line 636, in <module>
    syntax_parser()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "WebSocket_cURL.py", line 632, in syntax_parser
    data_to_send = data_handler.getArray()
UnboundLocalError: local variable 'data_handler' referenced before assignment
